lexik_jwt_authentication:
 secret_key: '%kernel.project_dir%/config/jwt/private.pem'
 public_key: '%kernel.project_dir%/config/jwt/public.pem'
 pass_phrase: 'your_secret_passphrase'  # Optionnel : la passphrase pour ta clé privée
 token_ttl: 3600  # Temps de vie du token en secondes
