security_logout:
    path: /api/logout
    controller: App\Controller\SecurityController::logout

security:
    firewalls:
        main:
            pattern: ^/api
            stateless: true
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password
            logout:
                path: /api/logout
