_security_logout:
    resource: security.route_loader.logout
    type: service

security:
    firewalls:
        main:
            json_login:
                check_path: api_login
                username_path: email
                password_path: password
