
"openapi": "3.0.0"
"info":
  "title": "Artist & Event API"
  "description": "API permettant de récupérer des artistes et des événements."
  "version": "1.0.0"
"servers":
  -
    "url": "http://127.0.0.1:8000/api"
"paths":
  "/artists":
    "get":
      "tags":
        - "Artist"
      "summary": "Récupère la liste de tous les artistes"
      "responses":
        "200":
          "description": "Liste des artistes"
          "content":
            "application/json":
              "schema":
                "type": "array"
                "items":
                  "type": "object"
                  "properties":
                    "id":
                      "type": "integer"
                    "name":
                      "type": "string"
                    "description":
                      "type": "string"
                    "imagePath":
                      "type": "string"
  "/artists/{artistId}":
    "get":
      "tags":
        - "Artist"
      "summary": "Récupère un artiste par ID"
      "parameters":
        -
          "name": "artistId"
          "in": "path"
          "required": true
          "description": "ID de l'artiste"
          "schema":
            "type": "integer"
      "responses":
        "200":
          "description": "Détails d'un artiste"
          "content":
            "application/json":
              "schema":
                "type": "object"
                "properties":
                  "id":
                    "type": "integer"
                  "name":
                    "type": "string"
                  "description":
                    "type": "string"
                  "imagePath":
                    "type": "string"
        "404":
          "description": "Artiste non trouvé"
  "/events":
    "get":
      "tags":
        - "Event"
      "summary": "Récupère la liste de tous les événements"
      "responses":
        "200":
          "description": "Liste des événements"
          "content":
            "application/json":
              "schema":
                "type": "array"
                "items":
                  "type": "object"
                  "properties":
                    "id":
                      "type": "integer"
                    "name":
                      "type": "string"
                    "date":
                      "type": "string"
                      "format": "date-time"
                    "artistId":
                      "type": "integer"
  "/events/{eventId}":
    "get":
      "tags":
        - "Event"
      "summary": "Récupère un événement par ID"
      "parameters":
        -
          "name": "eventId"
          "in": "path"
          "required": true
          "description": "ID de l'événement"
          "schema":
            "type": "integer"
      "responses":
        "200":
          "description": "Détails d'un événement"
          "content":
            "application/json":
              "schema":
                "type": "object"
                "properties":
                  "id":
                    "type": "integer"
                  "name":
                    "type": "string"
                  "date":
                    "type": "string"
                    "format": "date-time"
                  "artistId":
                    "type": "integer"
        "404":
          "description": "Événement non trouvé"
"components":
  "schemas":
    "Artist":
      "type": "object"
      "properties":
        "id":
          "type": "integer"
        "name":
          "type": "string"
        "description":
          "type": "string"
        "imagePath":
          "type": "string"
    "Event":
      "type": "object"
      "properties":
        "id":
          "type": "integer"
        "name":
          "type": "string"
        "date":
          "type": "string"
          "format": "date-time"
        "artistId":
          "type": "integer"