parameters:

services:
    # Charge tous les contrôleurs
    App\Controller\:
        resource: '../src/Controller/'
        tags: [ 'controller.service_arguments' ]

    # Configuration par défaut pour tous les services (autowire activé)
    _defaults:
        autowire: true
        autoconfigure: true

    # Rendre disponible les classes dans src/ comme services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
